source 'http://rubygems.org'

gem 'activerecord', '4.2.5', :require => 'active_record'
gem 'sinatra-activerecord', '>= 2.0.14', :require => 'sinatra/activerecord'

gem 'sinatra', '>= 2.0.2'
gem 'sqlite3'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake'
gem 'rspec'
gem 'rack-test', '>= 1.1.0'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'require_all'
gem 'json', '>=1.8.3'
